### ISSUE TITLE
"Reset Telemetry" doesn't actually reset telemetry data

### ISSUE THREAD

**Issue by brennan-macaig** [wpilibsuite/sysid#485] opened 2023-02-10 19:44 UTC
When a test has already been run (say, Dynamic Forward), the test can't be re-run without closing and re-opening sysid. Pressing the "reset telemetry" button doesn't actually reset the test results, as re-running the test produces an enabled robot which does not move.

**Comment by brennan-macaig** [comment] 2023-02-10 19:48
Possibly a duplicate of #408 ?

**Comment by calcmogul** [comment] 2023-09-29 23:15
I think the robot not moving is from the state machine on the robot side not being reset. That part of this issue is OBE by #518 (the robot code side was deleted).

The request for being able to rerun tests is a duplicate of #408.

**Closed by calcmogul** 2023-09-29 23:15 UTC
Labels: component: telemetry
