### ISSUE TITLE
Crash when loading old config

### ISSUE THREAD

**Issue by willtoth** [wpilibsuite/sysid#275] opened 2021-12-28 17:12 UTC
Since this is all in development there probably isn't a guarantee that an old config will work with newer builds. _However_ it still shouldn't crash the program.

Running on Windows 10 64-bit using v2022-1.1-beta4 (btw, you should make it so I can select the text in the info box so I can paste it here).

Loading the attached config crashes the program. I don't see any logs either in AppData or on the console
[mk2_swerve_sterring_config.zip](https://github.com/wpilibsuite/sysid/files/7785719/mk2_swerve_sterring_config.zip)
.

**Comment by Piphi5** [comment] 2021-12-29 03:16
@willtoth Can you see if the issue is fixed with the [build from this pr](https://github.com/wpilibsuite/sysid/actions/runs/1631611733)?

**Closed** 2021-12-31 03:42 UTC
Labels: bug, component: generation
