### ISSUE TITLE
CAN Status Frame Periods

### ISSUE THREAD

**Issue by Piphi5** [wpilibsuite/sysid#116] opened 2021-04-26 15:20 UTC
Currently, CAN Status Frame Periods are set to the defaults which means that sensor readings are updated at 10ms or 20ms (depending on the smart motor controller) which doesn't line up with the project's 5ms loop period. 

However, there seems to be issues with lowering these periods which causes the sensor readings to randomly be reset (probably need to figure out these issues with the vendors).

**Comment by calcmogul** [comment] 2021-04-26 15:38
The sensor readings resetting may be caused by CAN bus saturation and packet collisions. At least, that's what I saw when trying to set the SPARK MAX encoder position status frame to 10ms.

**Comment by calcmogul** [comment] 2021-05-26 15:42
If increasing the status frame periods for unnecessary data isn't enough to fix it, there's nothing else we can do. FRC's CAN spec doesn't let us manipulate the message IDs to specify message priority.

**Comment by calcmogul** [comment] 2021-10-15 20:37
I'm closing this since we don't plan on pursuing this further. If someone wants to revisit this, they can.

**Closed by calcmogul** 2021-10-15 20:37 UTC
Labels: component: generation
